### ISSUE TITLE
Stencil: Always get 'Cannot find tsconfig.base.json'

### ISSUE THREAD

**Issue by oliveirarafa** [nxext/nx-extensions#1083]
I don't know what I'm doing wrong but after creating a nx workspace I install `@nxext/stencil` and try to run `nx g @nxext/stencil:lib core-components --buildable` I get an error `Cannot find tsconfig.base.json`. Do i have to create it manually? What I put in it?

I use the following dependencies:

```json
"@nx/js": "18.0.0",
"@nxext/stencil": "^18.0.0",
"nx": "18.0.0"
```

**Comment by finikwashere** [comment]
While creating your organisation workspace using `npx create-nx-workspace`, you are given options to chose from. This error can occur due to recent developments in NX, while nxext can't keep up with all the possible multitude of options the NX Workspace now offers. One of the questions during the installation is:
```
? Integrated monorepo, or standalone project? … 
Integrated Monorepo:  Nx creates a monorepo that contains multiple projects.
Standalone:           Nx creates a single project and makes it fast.
```
The first option will create a folder structure, where the tsconfig is split into multiple files. One file for each project/lib you have and one parent file in the root of the org workspace folder, called `tsconfig.base.json`.
The second option will create a simple workspace with a minimum folder structure, which supports only one application and therefore it does not need to split/share the tsconfig.json into this project/parent config. It is still in root folder, but called `tsconfig.json`, not `tsconfig.base.json`.

The Stencil lib generator you are invoking was intended to be used in the integrated monorepo, where you have a `/libs` and `/apps` folders, but it didn't produce a graceful error, telling you you have a standalone project.

If you recreate your workspace as integrated monorepo, stencil lib generator will work properly.

**Comment by oliveirarafa** [comment]
Understood. I will try doing this. Using the newer versions gives a error too because of breaking changes on v20.

Thank you.
