### ISSUE TITLE
Nx test fails after creation of stencil library

### ISSUE THREAD

**Issue by TimSeyschab** [nxext/nx-extensions#309]
After creating a new empty nx workspace and creating a stencil library (nx g @nxext/stencil:lib my-lib), jest throws the following error.

```
$ nx run my-lib:test --verbose

>

> nx run my-lib:test --verbose 
[47:28.6]  testing spec  #files
[47:28.6]  jest args: --projectType=library --tsConfig=libs/my-lib/tsconfig.lib.json
           --configPath=libs/my-lib/stencil.config.ts --outputPath=dist/libs/my-lib --spec --max-workers=8

[ ERROR ]  runJest: TypeError: Class extends value #<Object> is not a constructor or null



Test Suites: 0 of 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0 s
———————————————————————————————————————————————

>  NX   ERROR  Running target "my-lib:test" failed

  Failed tasks:

  - my-lib:test

  Hint: run the command with --verbose for more details.
```

here is the package.json
[package.txt](https://github.com/nxext/nx-extensions/files/7148367/package.txt)

**Comment by ChrisKeck** [comment]
I also had this problem when migrating from NX11 to NX12. The cause was incompatible Jest dependencies. After all Jest dependencies were compatible with each other, it worked again. The only pain point is the non-migrated version of the plugin. I can only run it in version 11. All other NX plugins are version 12 :-( In my opinion, this is because: NX 12 brings Jest with version 27. Jest 27 does not yet work with StencilJS, see https://github.com/ionic-team/stencil/ issues / 2942 or https://github.com/ionic-team/stencil/issues/2922.
If anyone disagrees or has additional information, please share

**Comment by DominikPieper** [comment]
The main problem here is definitely the jest version. Something I try to override but unfortunately Nx does set the version of jest to 27. I wait for the stencil fix here eagerly

**Comment by TimSeyschab** [comment]
Using NX11 does work. Thank you Chris for linking to the issue in stencil-js. Guess I'll wait with the migration to 12 until they fixed the issue

**Comment by DominikPieper** [comment]
Today Stencil 2.13 came out with support for jest 27
